/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CanalizacoesRouteImport } from './routes/canalizacoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssociadosCadastroRouteImport } from './routes/associados.cadastro'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppUploadRouteImport } from './routes/_authenticated/app.upload'
import { Route as AuthenticatedAppRevisaoRouteImport } from './routes/_authenticated/app.revisao'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated/app.perfil'
import { Route as AuthenticatedAppPendenteRouteImport } from './routes/_authenticated/app.pendente'
import { Route as AuthenticatedAppMeusUploadsRouteImport } from './routes/_authenticated/app.meus-uploads'
import { Route as AuthenticatedAppEstoqueRouteImport } from './routes/_authenticated/app.estoque'
import { Route as AuthenticatedAppContaRouteImport } from './routes/_authenticated/app.conta'
import { Route as AuthenticatedAppAudiosRouteImport } from './routes/_authenticated/app.audios'
import { Route as AuthenticatedAppAcolhimentoRouteImport } from './routes/_authenticated/app.acolhimento'
import { Route as AuthenticatedAppTrabalhosIndexRouteImport } from './routes/_authenticated/app.trabalhos.index'
import { Route as AuthenticatedAppAudiosIndexRouteImport } from './routes/_authenticated/app.audios.index'
import { Route as AuthenticatedAppAssociadosIndexRouteImport } from './routes/_authenticated/app.associados.index'
import { Route as AuthenticatedAppAdminIndexRouteImport } from './routes/_authenticated/app.admin.index'
import { Route as AuthenticatedAppRevisaoIdRouteImport } from './routes/_authenticated/app.revisao.$id'
import { Route as AuthenticatedAppAudiosIdRouteImport } from './routes/_authenticated/app.audios.$id'
import { Route as AuthenticatedAppAssociadosTurmasRouteImport } from './routes/_authenticated/app.associados.turmas'
import { Route as AuthenticatedAppAssociadosIdRouteImport } from './routes/_authenticated/app.associados.$id'
import { Route as AuthenticatedAppAdminUsuariosRouteImport } from './routes/_authenticated/app.admin.usuarios'
import { Route as AuthenticatedAppAdminTrabalhosRouteImport } from './routes/_authenticated/app.admin.trabalhos'
import { Route as AuthenticatedAppAdminLogsRouteImport } from './routes/_authenticated/app.admin.logs'
import { Route as AuthenticatedAppAdminEntidadesRouteImport } from './routes/_authenticated/app.admin.entidades'
import { Route as AuthenticatedAppAdminCargosRouteImport } from './routes/_authenticated/app.admin.cargos'
import { Route as AuthenticatedAppAdminAudiosRouteImport } from './routes/_authenticated/app.admin.audios'
import { Route as AuthenticatedAppTrabalhosIdCheckinRouteImport } from './routes/_authenticated/app.trabalhos.$id.checkin'

const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CanalizacoesRoute = CanalizacoesRouteImport.update({
  id: '/canalizacoes',
  path: '/canalizacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociadosCadastroRoute = AssociadosCadastroRouteImport.update({
  id: '/associados/cadastro',
  path: '/associados/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppUploadRoute = AuthenticatedAppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRevisaoRoute = AuthenticatedAppRevisaoRouteImport.update({
  id: '/revisao',
  path: '/revisao',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPendenteRoute =
  AuthenticatedAppPendenteRouteImport.update({
    id: '/pendente',
    path: '/pendente',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMeusUploadsRoute =
  AuthenticatedAppMeusUploadsRouteImport.update({
    id: '/meus-uploads',
    path: '/meus-uploads',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEstoqueRoute = AuthenticatedAppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppContaRoute = AuthenticatedAppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAudiosRoute = AuthenticatedAppAudiosRouteImport.update({
  id: '/audios',
  path: '/audios',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAcolhimentoRoute =
  AuthenticatedAppAcolhimentoRouteImport.update({
    id: '/acolhimento',
    path: '/acolhimento',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTrabalhosIndexRoute =
  AuthenticatedAppTrabalhosIndexRouteImport.update({
    id: '/trabalhos/',
    path: '/trabalhos/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAudiosIndexRoute =
  AuthenticatedAppAudiosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAudiosRoute,
  } as any)
const AuthenticatedAppAssociadosIndexRoute =
  AuthenticatedAppAssociadosIndexRouteImport.update({
    id: '/associados/',
    path: '/associados/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminIndexRoute =
  AuthenticatedAppAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRevisaoIdRoute =
  AuthenticatedAppRevisaoIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppRevisaoRoute,
  } as any)
const AuthenticatedAppAudiosIdRoute =
  AuthenticatedAppAudiosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppAudiosRoute,
  } as any)
const AuthenticatedAppAssociadosTurmasRoute =
  AuthenticatedAppAssociadosTurmasRouteImport.update({
    id: '/associados/turmas',
    path: '/associados/turmas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAssociadosIdRoute =
  AuthenticatedAppAssociadosIdRouteImport.update({
    id: '/associados/$id',
    path: '/associados/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminUsuariosRoute =
  AuthenticatedAppAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminTrabalhosRoute =
  AuthenticatedAppAdminTrabalhosRouteImport.update({
    id: '/admin/trabalhos',
    path: '/admin/trabalhos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminLogsRoute =
  AuthenticatedAppAdminLogsRouteImport.update({
    id: '/admin/logs',
    path: '/admin/logs',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminEntidadesRoute =
  AuthenticatedAppAdminEntidadesRouteImport.update({
    id: '/admin/entidades',
    path: '/admin/entidades',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminCargosRoute =
  AuthenticatedAppAdminCargosRouteImport.update({
    id: '/admin/cargos',
    path: '/admin/cargos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminAudiosRoute =
  AuthenticatedAppAdminAudiosRouteImport.update({
    id: '/admin/audios',
    path: '/admin/audios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTrabalhosIdCheckinRoute =
  AuthenticatedAppTrabalhosIdCheckinRouteImport.update({
    id: '/trabalhos/$id/checkin',
    path: '/trabalhos/$id/checkin',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/canalizacoes': typeof CanalizacoesRoute
  '/contato': typeof ContatoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/associados/cadastro': typeof AssociadosCadastroRoute
  '/app/acolhimento': typeof AuthenticatedAppAcolhimentoRoute
  '/app/audios': typeof AuthenticatedAppAudiosRouteWithChildren
  '/app/conta': typeof AuthenticatedAppContaRoute
  '/app/estoque': typeof AuthenticatedAppEstoqueRoute
  '/app/meus-uploads': typeof AuthenticatedAppMeusUploadsRoute
  '/app/pendente': typeof AuthenticatedAppPendenteRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/revisao': typeof AuthenticatedAppRevisaoRouteWithChildren
  '/app/upload': typeof AuthenticatedAppUploadRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/audios': typeof AuthenticatedAppAdminAudiosRoute
  '/app/admin/cargos': typeof AuthenticatedAppAdminCargosRoute
  '/app/admin/entidades': typeof AuthenticatedAppAdminEntidadesRoute
  '/app/admin/logs': typeof AuthenticatedAppAdminLogsRoute
  '/app/admin/trabalhos': typeof AuthenticatedAppAdminTrabalhosRoute
  '/app/admin/usuarios': typeof AuthenticatedAppAdminUsuariosRoute
  '/app/associados/$id': typeof AuthenticatedAppAssociadosIdRoute
  '/app/associados/turmas': typeof AuthenticatedAppAssociadosTurmasRoute
  '/app/audios/$id': typeof AuthenticatedAppAudiosIdRoute
  '/app/revisao/$id': typeof AuthenticatedAppRevisaoIdRoute
  '/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/app/associados/': typeof AuthenticatedAppAssociadosIndexRoute
  '/app/audios/': typeof AuthenticatedAppAudiosIndexRoute
  '/app/trabalhos/': typeof AuthenticatedAppTrabalhosIndexRoute
  '/app/trabalhos/$id/checkin': typeof AuthenticatedAppTrabalhosIdCheckinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/canalizacoes': typeof CanalizacoesRoute
  '/contato': typeof ContatoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/associados/cadastro': typeof AssociadosCadastroRoute
  '/app/acolhimento': typeof AuthenticatedAppAcolhimentoRoute
  '/app/conta': typeof AuthenticatedAppContaRoute
  '/app/estoque': typeof AuthenticatedAppEstoqueRoute
  '/app/meus-uploads': typeof AuthenticatedAppMeusUploadsRoute
  '/app/pendente': typeof AuthenticatedAppPendenteRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/revisao': typeof AuthenticatedAppRevisaoRouteWithChildren
  '/app/upload': typeof AuthenticatedAppUploadRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/audios': typeof AuthenticatedAppAdminAudiosRoute
  '/app/admin/cargos': typeof AuthenticatedAppAdminCargosRoute
  '/app/admin/entidades': typeof AuthenticatedAppAdminEntidadesRoute
  '/app/admin/logs': typeof AuthenticatedAppAdminLogsRoute
  '/app/admin/trabalhos': typeof AuthenticatedAppAdminTrabalhosRoute
  '/app/admin/usuarios': typeof AuthenticatedAppAdminUsuariosRoute
  '/app/associados/$id': typeof AuthenticatedAppAssociadosIdRoute
  '/app/associados/turmas': typeof AuthenticatedAppAssociadosTurmasRoute
  '/app/audios/$id': typeof AuthenticatedAppAudiosIdRoute
  '/app/revisao/$id': typeof AuthenticatedAppRevisaoIdRoute
  '/app/admin': typeof AuthenticatedAppAdminIndexRoute
  '/app/associados': typeof AuthenticatedAppAssociadosIndexRoute
  '/app/audios': typeof AuthenticatedAppAudiosIndexRoute
  '/app/trabalhos': typeof AuthenticatedAppTrabalhosIndexRoute
  '/app/trabalhos/$id/checkin': typeof AuthenticatedAppTrabalhosIdCheckinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/canalizacoes': typeof CanalizacoesRoute
  '/contato': typeof ContatoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/associados/cadastro': typeof AssociadosCadastroRoute
  '/_authenticated/app/acolhimento': typeof AuthenticatedAppAcolhimentoRoute
  '/_authenticated/app/audios': typeof AuthenticatedAppAudiosRouteWithChildren
  '/_authenticated/app/conta': typeof AuthenticatedAppContaRoute
  '/_authenticated/app/estoque': typeof AuthenticatedAppEstoqueRoute
  '/_authenticated/app/meus-uploads': typeof AuthenticatedAppMeusUploadsRoute
  '/_authenticated/app/pendente': typeof AuthenticatedAppPendenteRoute
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/revisao': typeof AuthenticatedAppRevisaoRouteWithChildren
  '/_authenticated/app/upload': typeof AuthenticatedAppUploadRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/audios': typeof AuthenticatedAppAdminAudiosRoute
  '/_authenticated/app/admin/cargos': typeof AuthenticatedAppAdminCargosRoute
  '/_authenticated/app/admin/entidades': typeof AuthenticatedAppAdminEntidadesRoute
  '/_authenticated/app/admin/logs': typeof AuthenticatedAppAdminLogsRoute
  '/_authenticated/app/admin/trabalhos': typeof AuthenticatedAppAdminTrabalhosRoute
  '/_authenticated/app/admin/usuarios': typeof AuthenticatedAppAdminUsuariosRoute
  '/_authenticated/app/associados/$id': typeof AuthenticatedAppAssociadosIdRoute
  '/_authenticated/app/associados/turmas': typeof AuthenticatedAppAssociadosTurmasRoute
  '/_authenticated/app/audios/$id': typeof AuthenticatedAppAudiosIdRoute
  '/_authenticated/app/revisao/$id': typeof AuthenticatedAppRevisaoIdRoute
  '/_authenticated/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/_authenticated/app/associados/': typeof AuthenticatedAppAssociadosIndexRoute
  '/_authenticated/app/audios/': typeof AuthenticatedAppAudiosIndexRoute
  '/_authenticated/app/trabalhos/': typeof AuthenticatedAppTrabalhosIndexRoute
  '/_authenticated/app/trabalhos/$id/checkin': typeof AuthenticatedAppTrabalhosIdCheckinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auth'
    | '/canalizacoes'
    | '/contato'
    | '/quem-somos'
    | '/app'
    | '/associados/cadastro'
    | '/app/acolhimento'
    | '/app/audios'
    | '/app/conta'
    | '/app/estoque'
    | '/app/meus-uploads'
    | '/app/pendente'
    | '/app/perfil'
    | '/app/revisao'
    | '/app/upload'
    | '/app/'
    | '/app/admin/audios'
    | '/app/admin/cargos'
    | '/app/admin/entidades'
    | '/app/admin/logs'
    | '/app/admin/trabalhos'
    | '/app/admin/usuarios'
    | '/app/associados/$id'
    | '/app/associados/turmas'
    | '/app/audios/$id'
    | '/app/revisao/$id'
    | '/app/admin/'
    | '/app/associados/'
    | '/app/audios/'
    | '/app/trabalhos/'
    | '/app/trabalhos/$id/checkin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/auth'
    | '/canalizacoes'
    | '/contato'
    | '/quem-somos'
    | '/associados/cadastro'
    | '/app/acolhimento'
    | '/app/conta'
    | '/app/estoque'
    | '/app/meus-uploads'
    | '/app/pendente'
    | '/app/perfil'
    | '/app/revisao'
    | '/app/upload'
    | '/app'
    | '/app/admin/audios'
    | '/app/admin/cargos'
    | '/app/admin/entidades'
    | '/app/admin/logs'
    | '/app/admin/trabalhos'
    | '/app/admin/usuarios'
    | '/app/associados/$id'
    | '/app/associados/turmas'
    | '/app/audios/$id'
    | '/app/revisao/$id'
    | '/app/admin'
    | '/app/associados'
    | '/app/audios'
    | '/app/trabalhos'
    | '/app/trabalhos/$id/checkin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agenda'
    | '/auth'
    | '/canalizacoes'
    | '/contato'
    | '/quem-somos'
    | '/_authenticated/app'
    | '/associados/cadastro'
    | '/_authenticated/app/acolhimento'
    | '/_authenticated/app/audios'
    | '/_authenticated/app/conta'
    | '/_authenticated/app/estoque'
    | '/_authenticated/app/meus-uploads'
    | '/_authenticated/app/pendente'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/revisao'
    | '/_authenticated/app/upload'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/audios'
    | '/_authenticated/app/admin/cargos'
    | '/_authenticated/app/admin/entidades'
    | '/_authenticated/app/admin/logs'
    | '/_authenticated/app/admin/trabalhos'
    | '/_authenticated/app/admin/usuarios'
    | '/_authenticated/app/associados/$id'
    | '/_authenticated/app/associados/turmas'
    | '/_authenticated/app/audios/$id'
    | '/_authenticated/app/revisao/$id'
    | '/_authenticated/app/admin/'
    | '/_authenticated/app/associados/'
    | '/_authenticated/app/audios/'
    | '/_authenticated/app/trabalhos/'
    | '/_authenticated/app/trabalhos/$id/checkin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  CanalizacoesRoute: typeof CanalizacoesRoute
  ContatoRoute: typeof ContatoRoute
  QuemSomosRoute: typeof QuemSomosRoute
  AssociadosCadastroRoute: typeof AssociadosCadastroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canalizacoes': {
      id: '/canalizacoes'
      path: '/canalizacoes'
      fullPath: '/canalizacoes'
      preLoaderRoute: typeof CanalizacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/associados/cadastro': {
      id: '/associados/cadastro'
      path: '/associados/cadastro'
      fullPath: '/associados/cadastro'
      preLoaderRoute: typeof AssociadosCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/upload': {
      id: '/_authenticated/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AuthenticatedAppUploadRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/revisao': {
      id: '/_authenticated/app/revisao'
      path: '/revisao'
      fullPath: '/app/revisao'
      preLoaderRoute: typeof AuthenticatedAppRevisaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pendente': {
      id: '/_authenticated/app/pendente'
      path: '/pendente'
      fullPath: '/app/pendente'
      preLoaderRoute: typeof AuthenticatedAppPendenteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/meus-uploads': {
      id: '/_authenticated/app/meus-uploads'
      path: '/meus-uploads'
      fullPath: '/app/meus-uploads'
      preLoaderRoute: typeof AuthenticatedAppMeusUploadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/estoque': {
      id: '/_authenticated/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AuthenticatedAppEstoqueRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/conta': {
      id: '/_authenticated/app/conta'
      path: '/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AuthenticatedAppContaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/audios': {
      id: '/_authenticated/app/audios'
      path: '/audios'
      fullPath: '/app/audios'
      preLoaderRoute: typeof AuthenticatedAppAudiosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/acolhimento': {
      id: '/_authenticated/app/acolhimento'
      path: '/acolhimento'
      fullPath: '/app/acolhimento'
      preLoaderRoute: typeof AuthenticatedAppAcolhimentoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/trabalhos/': {
      id: '/_authenticated/app/trabalhos/'
      path: '/trabalhos'
      fullPath: '/app/trabalhos/'
      preLoaderRoute: typeof AuthenticatedAppTrabalhosIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/audios/': {
      id: '/_authenticated/app/audios/'
      path: '/'
      fullPath: '/app/audios/'
      preLoaderRoute: typeof AuthenticatedAppAudiosIndexRouteImport
      parentRoute: typeof AuthenticatedAppAudiosRoute
    }
    '/_authenticated/app/associados/': {
      id: '/_authenticated/app/associados/'
      path: '/associados'
      fullPath: '/app/associados/'
      preLoaderRoute: typeof AuthenticatedAppAssociadosIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/': {
      id: '/_authenticated/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AuthenticatedAppAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/revisao/$id': {
      id: '/_authenticated/app/revisao/$id'
      path: '/$id'
      fullPath: '/app/revisao/$id'
      preLoaderRoute: typeof AuthenticatedAppRevisaoIdRouteImport
      parentRoute: typeof AuthenticatedAppRevisaoRoute
    }
    '/_authenticated/app/audios/$id': {
      id: '/_authenticated/app/audios/$id'
      path: '/$id'
      fullPath: '/app/audios/$id'
      preLoaderRoute: typeof AuthenticatedAppAudiosIdRouteImport
      parentRoute: typeof AuthenticatedAppAudiosRoute
    }
    '/_authenticated/app/associados/turmas': {
      id: '/_authenticated/app/associados/turmas'
      path: '/associados/turmas'
      fullPath: '/app/associados/turmas'
      preLoaderRoute: typeof AuthenticatedAppAssociadosTurmasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/associados/$id': {
      id: '/_authenticated/app/associados/$id'
      path: '/associados/$id'
      fullPath: '/app/associados/$id'
      preLoaderRoute: typeof AuthenticatedAppAssociadosIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/usuarios': {
      id: '/_authenticated/app/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/app/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAppAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/trabalhos': {
      id: '/_authenticated/app/admin/trabalhos'
      path: '/admin/trabalhos'
      fullPath: '/app/admin/trabalhos'
      preLoaderRoute: typeof AuthenticatedAppAdminTrabalhosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/logs': {
      id: '/_authenticated/app/admin/logs'
      path: '/admin/logs'
      fullPath: '/app/admin/logs'
      preLoaderRoute: typeof AuthenticatedAppAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/entidades': {
      id: '/_authenticated/app/admin/entidades'
      path: '/admin/entidades'
      fullPath: '/app/admin/entidades'
      preLoaderRoute: typeof AuthenticatedAppAdminEntidadesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/cargos': {
      id: '/_authenticated/app/admin/cargos'
      path: '/admin/cargos'
      fullPath: '/app/admin/cargos'
      preLoaderRoute: typeof AuthenticatedAppAdminCargosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/audios': {
      id: '/_authenticated/app/admin/audios'
      path: '/admin/audios'
      fullPath: '/app/admin/audios'
      preLoaderRoute: typeof AuthenticatedAppAdminAudiosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/trabalhos/$id/checkin': {
      id: '/_authenticated/app/trabalhos/$id/checkin'
      path: '/trabalhos/$id/checkin'
      fullPath: '/app/trabalhos/$id/checkin'
      preLoaderRoute: typeof AuthenticatedAppTrabalhosIdCheckinRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppAudiosRouteChildren {
  AuthenticatedAppAudiosIdRoute: typeof AuthenticatedAppAudiosIdRoute
  AuthenticatedAppAudiosIndexRoute: typeof AuthenticatedAppAudiosIndexRoute
}

const AuthenticatedAppAudiosRouteChildren: AuthenticatedAppAudiosRouteChildren =
  {
    AuthenticatedAppAudiosIdRoute: AuthenticatedAppAudiosIdRoute,
    AuthenticatedAppAudiosIndexRoute: AuthenticatedAppAudiosIndexRoute,
  }

const AuthenticatedAppAudiosRouteWithChildren =
  AuthenticatedAppAudiosRoute._addFileChildren(
    AuthenticatedAppAudiosRouteChildren,
  )

interface AuthenticatedAppRevisaoRouteChildren {
  AuthenticatedAppRevisaoIdRoute: typeof AuthenticatedAppRevisaoIdRoute
}

const AuthenticatedAppRevisaoRouteChildren: AuthenticatedAppRevisaoRouteChildren =
  {
    AuthenticatedAppRevisaoIdRoute: AuthenticatedAppRevisaoIdRoute,
  }

const AuthenticatedAppRevisaoRouteWithChildren =
  AuthenticatedAppRevisaoRoute._addFileChildren(
    AuthenticatedAppRevisaoRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAcolhimentoRoute: typeof AuthenticatedAppAcolhimentoRoute
  AuthenticatedAppAudiosRoute: typeof AuthenticatedAppAudiosRouteWithChildren
  AuthenticatedAppContaRoute: typeof AuthenticatedAppContaRoute
  AuthenticatedAppEstoqueRoute: typeof AuthenticatedAppEstoqueRoute
  AuthenticatedAppMeusUploadsRoute: typeof AuthenticatedAppMeusUploadsRoute
  AuthenticatedAppPendenteRoute: typeof AuthenticatedAppPendenteRoute
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppRevisaoRoute: typeof AuthenticatedAppRevisaoRouteWithChildren
  AuthenticatedAppUploadRoute: typeof AuthenticatedAppUploadRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAdminAudiosRoute: typeof AuthenticatedAppAdminAudiosRoute
  AuthenticatedAppAdminCargosRoute: typeof AuthenticatedAppAdminCargosRoute
  AuthenticatedAppAdminEntidadesRoute: typeof AuthenticatedAppAdminEntidadesRoute
  AuthenticatedAppAdminLogsRoute: typeof AuthenticatedAppAdminLogsRoute
  AuthenticatedAppAdminTrabalhosRoute: typeof AuthenticatedAppAdminTrabalhosRoute
  AuthenticatedAppAdminUsuariosRoute: typeof AuthenticatedAppAdminUsuariosRoute
  AuthenticatedAppAssociadosIdRoute: typeof AuthenticatedAppAssociadosIdRoute
  AuthenticatedAppAssociadosTurmasRoute: typeof AuthenticatedAppAssociadosTurmasRoute
  AuthenticatedAppAdminIndexRoute: typeof AuthenticatedAppAdminIndexRoute
  AuthenticatedAppAssociadosIndexRoute: typeof AuthenticatedAppAssociadosIndexRoute
  AuthenticatedAppTrabalhosIndexRoute: typeof AuthenticatedAppTrabalhosIndexRoute
  AuthenticatedAppTrabalhosIdCheckinRoute: typeof AuthenticatedAppTrabalhosIdCheckinRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAcolhimentoRoute: AuthenticatedAppAcolhimentoRoute,
  AuthenticatedAppAudiosRoute: AuthenticatedAppAudiosRouteWithChildren,
  AuthenticatedAppContaRoute: AuthenticatedAppContaRoute,
  AuthenticatedAppEstoqueRoute: AuthenticatedAppEstoqueRoute,
  AuthenticatedAppMeusUploadsRoute: AuthenticatedAppMeusUploadsRoute,
  AuthenticatedAppPendenteRoute: AuthenticatedAppPendenteRoute,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppRevisaoRoute: AuthenticatedAppRevisaoRouteWithChildren,
  AuthenticatedAppUploadRoute: AuthenticatedAppUploadRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAdminAudiosRoute: AuthenticatedAppAdminAudiosRoute,
  AuthenticatedAppAdminCargosRoute: AuthenticatedAppAdminCargosRoute,
  AuthenticatedAppAdminEntidadesRoute: AuthenticatedAppAdminEntidadesRoute,
  AuthenticatedAppAdminLogsRoute: AuthenticatedAppAdminLogsRoute,
  AuthenticatedAppAdminTrabalhosRoute: AuthenticatedAppAdminTrabalhosRoute,
  AuthenticatedAppAdminUsuariosRoute: AuthenticatedAppAdminUsuariosRoute,
  AuthenticatedAppAssociadosIdRoute: AuthenticatedAppAssociadosIdRoute,
  AuthenticatedAppAssociadosTurmasRoute: AuthenticatedAppAssociadosTurmasRoute,
  AuthenticatedAppAdminIndexRoute: AuthenticatedAppAdminIndexRoute,
  AuthenticatedAppAssociadosIndexRoute: AuthenticatedAppAssociadosIndexRoute,
  AuthenticatedAppTrabalhosIndexRoute: AuthenticatedAppTrabalhosIndexRoute,
  AuthenticatedAppTrabalhosIdCheckinRoute:
    AuthenticatedAppTrabalhosIdCheckinRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  CanalizacoesRoute: CanalizacoesRoute,
  ContatoRoute: ContatoRoute,
  QuemSomosRoute: QuemSomosRoute,
  AssociadosCadastroRoute: AssociadosCadastroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
