/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CanalizacoesRouteImport } from './routes/canalizacoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CanalizacoesRoute = CanalizacoesRouteImport.update({
  id: '/canalizacoes',
  path: '/canalizacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/canalizacoes': typeof CanalizacoesRoute
  '/contato': typeof ContatoRoute
  '/quem-somos': typeof QuemSomosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/canalizacoes': typeof CanalizacoesRoute
  '/contato': typeof ContatoRoute
  '/quem-somos': typeof QuemSomosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/canalizacoes': typeof CanalizacoesRoute
  '/contato': typeof ContatoRoute
  '/quem-somos': typeof QuemSomosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auth'
    | '/canalizacoes'
    | '/contato'
    | '/quem-somos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agenda' | '/auth' | '/canalizacoes' | '/contato' | '/quem-somos'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/auth'
    | '/canalizacoes'
    | '/contato'
    | '/quem-somos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  CanalizacoesRoute: typeof CanalizacoesRoute
  ContatoRoute: typeof ContatoRoute
  QuemSomosRoute: typeof QuemSomosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canalizacoes': {
      id: '/canalizacoes'
      path: '/canalizacoes'
      fullPath: '/canalizacoes'
      preLoaderRoute: typeof CanalizacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  CanalizacoesRoute: CanalizacoesRoute,
  ContatoRoute: ContatoRoute,
  QuemSomosRoute: QuemSomosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
